### PR TITLE
CharSequenceAccess supports unalign offsets

### LINKED ISSUE #36: CharSequenceAccess return wrong short/int/long value if offset is odd
```java

// on little endian machine

CharSequenceAccess a = CharSequenceAccess.nativeCharSequenceAccess();
assertEquals((short)65, (short)a.getShort("AB", 0)); // correct
assertEquals((short)(66<<8), (short)a.getShort("AB", 1)); // exception
```

`getByte()` is correct via a `shift` parameter, but short/int/long seems to assume offset is always even. It is not exploded by Access interface that CharSequenceAccess cannot deal the alignment.

### PR DESCRIPTION
**Pull request by gzm55**
detect unalign offsets in runtime. this may take in a little performance cost, but should work. all ut cases are designed for little endian machines.

Close #36

### CODE REVIEW

File: src/main/java/net/openhft/hashing/CharSequenceAccess.java [hunk 1]
```diff
@@ -114,12 +143,17 @@ private BigEndianCharSequenceAccess() {}
 
         @Override
         public long getLong(CharSequence input, long offset) {
-            return getLong(input, offset, 3, 2, 1, 0);
+            return getLong(input, offset, 3, 2, 1, 0, 0, 1);
```
Comment (leventov) [inline src/main/java/net/openhft/hashing/CharSequenceAccess.java]: Looks strange that this is not as symmetric as little-endian, logically there should be -1 after 0. Did you test this?

File: src/main/java/net/openhft/hashing/CharSequenceAccess.java [hunk 2]
```diff
@@ -37,22 +37,55 @@ private static int ix(long offset) {
...
+            final long char1 = input.charAt(base + char1Off);
+            final long char2 = input.charAt(base + char2Off);
+            final long char3 = input.charAt(base + char3Off);
+            return char0 | (char1 << 16) | (char2 << 32) | (char3 << 48);
+        } else {
+            final long char0 = input.charAt(base + char0Off + delta) >>> 8;
+            final long char1 = input.charAt(base + char1Off + delta);
+            final long char2 = input.charAt(base + char2Off + delta);
+            final long char3 = input.charAt(base + char3Off + delta);
+            final long char4 = input.charAt(base + char4Off);
```
Comment (leventov) [inline src/main/java/net/openhft/hashing/CharSequenceAccess.java]: Note that you must not query a single byte outside of the range: e. g. a sequence of 9 bytes (`new byte[9]`) and you query long at offset 1 - you must not try to pull 10 bytes (as you apparently do now) because the 10th byte may be outside of the allowed area.

Comment (gzm55) [reply src/main/java/net/openhft/hashing/CharSequenceAccess.java]: `CharSequenceAccess` delegate all memory read operations to `CharSequence.charAt()`, so the boundary of querying could at `char` level, not `byte` level. Suppose we could use `CharSeqenceAccess` to wrap a `b=byte[9]` array, then `access.getByte(b, 8)` (this method is not changed in this pr) will also read beyond the byte boundary, that is, `input.charAt(9>>2)` will eventually query `b[8]` and `b[9]`.

imo, this is a flaw from the birthday of CharSequenceAccess, so we have to not use this access implementation to query an odd byte length memory. luckily, this should be always true for `java.lang.CharSequence`.

File: src/main/java/net/openhft/hashing/CharSequenceAccess.java (hunk 1 above)
Comment (gzm55) [reply src/main/java/net/openhft/hashing/CharSequenceAccess.java]: the two new arguments are only used when offset is misaligned:
- the `Off` of the highest char when offset is unalign, i.e. `char4Off` for `getLong()`
- the delta for other chars

For example, in little-endian `getLong()`

- char0: align=0 unalign=0 + **0**
- char1: align=1 unalign=1 + **0**
- char2: align=2 unalign=2 + **0**
- char3: align=3 unalign=3 + **0**
- char4:                unalign=**4**

in big-endian `getLong()`

- char0: align=3 unalign=3 + **1**
- char1: align=2 unalign=2 + **1**
- char2: align=1 unalign=1 + **1**
- char3: align=0 unalign=0 + **1**
- char4:                unalign=**4**


All `Access` public methods have passed the ut in `CharSequenceAccessTest.java` for both little- and big- endians.

File: src/main/java/net/openhft/hashing/CharSequenceAccess.java (hunk 2 above)
Comment (leventov) [reply src/main/java/net/openhft/hashing/CharSequenceAccess.java]: You are right, I missed that we are accessing CharSequences anyway

File: src/main/java/net/openhft/hashing/CharSequenceAccess.java (hunk 1 above)
Comment (leventov) [reply src/main/java/net/openhft/hashing/CharSequenceAccess.java]: Ok

**Comment by leventov** [comment]
@gzm55 feel free to merge when ready, don't consider me as a gatekeeper (in this PR, and in general in this repo)

**Comment by gzm55** [comment]
@leventov ok~

**Comment by RobAustin** [comment]
James. - let me know when you want this released.

**Comment by gzm55** [comment]
This bug only affects `hash(input, access, input, length)` method, so it can be release at any convenient time.


Now the `hashChars()` methods will always pass an even `length` and an even `offset` to `hash(input, access, input, length)` method, and all the implementations internally fetch `short/int/long` at `A*offset+B*length+2*C` byte positions. Therefore `hashChars()` are safe. In v0.11, it will give out incorrect result only when we directly call `hash(input, access, input, length)` in a rare way, such as the following code will fail:

```java
String str = "ABC";
byte[] b = new byte[] {0, (byte)'B', 0, (byte)'C'};
assertEquals(f.hashBytes(b), f.hash(str, nativeCharSequenceAccess(), 1, 4));
```
